"""
Compatibility shim that re-exports the scoreboard helpers from the tictactoe package.
"""

from tictactoe.scoreboard import (
    BASE_DIR,
    DATA_DIR,
    SCOREBOARD_DIR,
    SCOREBOARD_FILE,
    SCOREBOARD_BACKUP,
    MATCH_SCOREBOARD_FILE,
    MATCH_SCOREBOARD_BACKUP,
    SAFE_MODE,
    SAFE_MODE_MESSAGE,
    DIFFICULTIES,
    DEFAULT_SCORE,
    SCORE_HASH_KEY,
    SCORE_DATA_KEY,
    SCORE_PREV_KEY,
    new_scoreboard,
    print_scoreboard,
    print_match_scoreboard,
    set_safe_mode,
    load_scoreboard,
    save_scoreboard,
    load_match_scoreboard,
    save_match_scoreboard,
    maybe_reset_scoreboard,
)

__all__ = [
    "BASE_DIR",
    "DATA_DIR",
    "SCOREBOARD_DIR",
    "SCOREBOARD_FILE",
    "SCOREBOARD_BACKUP",
    "MATCH_SCOREBOARD_FILE",
    "MATCH_SCOREBOARD_BACKUP",
    "SAFE_MODE",
    "SAFE_MODE_MESSAGE",
    "DIFFICULTIES",
    "DEFAULT_SCORE",
    "SCORE_HASH_KEY",
    "SCORE_DATA_KEY",
    "SCORE_PREV_KEY",
    "new_scoreboard",
    "print_scoreboard",
    "print_match_scoreboard",
    "set_safe_mode",
    "load_scoreboard",
    "save_scoreboard",
    "load_match_scoreboard",
    "save_match_scoreboard",
    "maybe_reset_scoreboard",
]